#!/bin/sh
. "$PROJECT_PATH/_environment.sh"
file_msg "$(basename "$0")"

#####################################################
# EXPORTS

# NEW LEMP STACK
export NEW_STACK_NAME="${LEMP_SERVER_DOMAIN_NAME}"
export NEW_STACK_PATH="${STACKS_PATH}/${LEMP_SERVER_DOMAIN_NAME}"

# LEMP SERVER
export LEMP_DIR="${NEW_STACK_NAME}"

# LEMP Stack Container
export LEMP_CONTAINER_NAME="${LEMP_SERVER_DOMAIN_NAME}_lemp"
export LEMP_PATH="${NEW_STACK_PATH}"

# LEMP Docker Compose .yaml File
export LEMP_DOCKER_COMPOSE_YML="${LEMP_PATH}/docker-compose.yml"
export LEMP_NETWORK_NAME="${LEMP_CONTAINER_NAME}_network"

# DIRECTORIES
export PHP_PUBLIC_DIR="html"
export PHP_PUBLIC_PATH="${LEMP_PATH}/${PHP_PUBLIC_DIR}"

# SECRETS
export SECRETS_DIR="secrets"
export LEMP_SECRETS_PATH="${LEMP_PATH}/${SECRETS_DIR}"

# DATABASE
export DB_DIR="database"
export DB_DATA_DIR="data"
export DB_PATH="$LEMP_PATH/${DB_DIR}"
export DB_DATA_PATH="${DB_PATH}/${DB_DATA_DIR}"
# PATH INSIDE THE CONTAINER
export DB_CONTAINER_DATA_PATH="/var/lib/mysql"

# BACKUPS
export BACKUPS_CONTAINER_NAME="${LEMP_SERVER_DOMAIN_NAME}-backups"
export BACKUPS_DIR="backups"
export BACKUPS_PATH="${DB_PATH}/${BACKUPS_DIR}"
export BACKUPS_CRONTAB_FILE="${BACKUPS_PATH}/crontab"
export BACKUPS_SCRIPTS_DIR="scripts"
export BACKUPS_SCRIPTS_PATH="${LEMP_PATH}/${BACKUPS_SCRIPTS_DIR}"
export BACKUPS_CLEANUP_SCRIPT_FILE="lemp-cleanup-backups.sh"
export BACKUPS_CLEANUP_SCRIPT_FILE_PATH="${BACKUPS_SCRIPTS_PATH}/${BACKUPS_CLEANUP_SCRIPT_FILE}"
# PATH INSIDE THE CONTAINER
export BACKUPS_CONTAINER_BACKUPS_PATH="/${BACKUPS_CONTAINER_NAME}/${BACKUPS_DIR}"
export BACKUPS_CONTAINER_GHOST_BACKUPS_PATH="/${BACKUPS_CONTAINER_NAME}/${BACKUPS_DIR}-ghost"

# DATABASE SECRETS
export DB_ROOT_USER_FILE="${LEMP_SECRETS_PATH}/db_root_user.txt"
export DB_ROOT_USER_PASSWORD_FILE="${LEMP_SECRETS_PATH}/db_root_user_password.txt"

# CONTAINERS
export CONTAINERS_DIR="containers"
export LEMP_CONTAINERS_PATH="${LEMP_PATH}/${CONTAINERS_DIR}"

# .ENV
export LEMP_ENV_FILE="${LEMP_PATH}/.env"

# PHP
export PHP_CONTAINER_NAME="${LEMP_SERVER_DOMAIN_NAME}-php-fpm"
export PHP_DIR="php"
export LEMP_PHP_PATH="${LEMP_PATH}/${PHP_DIR}"
export LEMP_PHP_FILE_INI="${LEMP_PATH}/${PHP_DIR}/php.ini"

# PHPMYADMIN
export PHPMYADMIN_CONTAINER_NAME="${LEMP_SERVER_DOMAIN_NAME}-phpmyadmin"
export PHPMYADMIN_DIR="phpmyadmin"
export PHPMYADMIN_PATH="${LEMP_PATH}/${PHPMYADMIN_DIR}"
export PHPMYADMIN_FILE_CONF="${PHPMYADMIN_PATH}/phpmyadmin.conf"

# NGINX
export NGINX_CONTAINER_NAME="${LEMP_SERVER_DOMAIN_NAME}-nginx"
export NGINX_DIR="nginx"
# Paths for LEMP NGINX Configuration files
export NGINX_CONF_DIR="conf.d"
export LEMP_NGINX_PATH="${LEMP_PATH}/${NGINX_DIR}"
export LEMP_NGINX_CONF_PATH="${LEMP_NGINX_PATH}/conf.d"
export LEMP_NGINX_CONF_FILE="${LEMP_NGINX_CONF_PATH}/default.conf"
export LEMP_NGINX_CATCHALL_CONF_FILE="${LEMP_NGINX_CONF_PATH}/catchall.conf"

# TRAEFIK CONFIG.YML FOR LEMP STACK
export LEMP_TRAEFIK_CONFIG_YML_FILE="${TRAEFIK_DYNAMIC_PATH}/lemp-${LEMP_SERVER_DOMAIN_NAME}.yml"

# SSL CERTIFICATES
export LEMP_TRAEFIK_DOMAIN_SSL_CRT_FILE="${TRAEFIK_CERTS_PATH}/${LEMP_SERVER_DOMAIN}.crt"
export LEMP_TRAEFIK_DOMAIN_SSL_KEY_FILE="${TRAEFIK_CERTS_PATH}/${LEMP_SERVER_DOMAIN}.key"

# LOG
export LOG_DIR="log"
export LOG_PATH="${LEMP_PATH}/${LOG_DIR}"
export LOG_CONTAINER_PATH="/var/log"

#####################################################
# CONTINUE TO CREATE LEMP STACK
sh "${SCRIPTS_PATH}/lemp/create-lemp/create-lemp-4-directory.sh"
