#
# Resolve project and stacks paths if not provided
: ${PROJECT_PATH:=$(cd "$(dirname "$0")/../.." && pwd)}
: ${STACKS_PATH:="$PROJECT_PATH/stacks"}
#!/bin/sh
OVERRIDE_FILE="$PROJECT_PATH/traefik/docker-compose.override.yml"


# Collect aliases from stacks and WP sites
aliases=""
for env_file in $(find "$STACKS_PATH" -type f -name ".env"); do
  # Read lines from .env file
  while IFS= read -r line; do
    case "$line" in
      STACK_DOMAIN=*)
        domain=${line#STACK_DOMAIN=}
        aliases="$aliases $domain"
        ;;
      PMA_DOMAIN=*)
        domain=${line#PMA_DOMAIN=}
        aliases="$aliases $domain"
        ;;
      SITE_DOMAIN=*)
        domain=${line#SITE_DOMAIN=}
        aliases="$aliases $domain"
        ;;
    esac
  done < "$env_file"
done

# Deduplicate and sort aliases
# Use tr, sort, uniq to process aliases
aliases=$(printf "%s\n" $aliases | sort -u)

{
  echo "# AUTO-GENERATED: Do not edit by hand."
  echo "# Regenerated by scripts/traefik/update-traefik-network-overrides.sh"
  echo "services:"
  echo "  traefik:"
  echo "    networks:"
  echo "      traefik_network:"
  echo "        aliases:"
  for alias in $aliases; do
    echo "          - $alias"
  done
} > "$OVERRIDE_FILE"